@Api_HostAddress = http://localhost:5184

GET {{Api_HostAddress}}/weatherforecast/
Accept: application/json

### Teste do Login
POST {{Api_HostAddress}}/auth/login
Content-Type: application/json

{
  "email": "admin@euajudo.org",
  "password": "Admin@123"
}